export const GET_VIDEO_DETAILS = "GET_VIDEO_DETAILS";
export const GET_VIDEO_RECOMENDATIONS = "GET_VIDEO_RECOMENDATIONS";
export const GET_COMMENTS = "GET_COMMENTS";
export const RESET_STORE = "RESET_STORE";
